CREATE TABLE IF NOT EXISTS Employees(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
FirstName TEXT NOT NULL,
LastName TEXT NOT NULL,
JobTitle TEXT,
Team TEXT,
WorksFromHome INTEGER DEFAULT 0,
Email TEXT,
CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
IsActive INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS LoginUsers(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
EmployeeId INTEGER,
EmailAddress TEXT UNIQUE NOT NULL, 
Username TEXT NOT NULL,
PasswordHash TEXT NOT NULL,
Role TEXT NOT NULL,
CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
IsActive INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS AssetTypes(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL,
IsActive INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Inventory(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
AssetTag TEXT UNIQUE NOT NULL,
AssetTypeId INTEGER NOT NULL,
Manufacturer TEXT,
SerialNumber TEXT,
PurchaseDate TEXT,
Status TEXT NOT NULL,
AssignedEmployeeId INTEGER,
DateAssigned TEXT,
Condition TEXT,
CurrentLocation TEXT,
Notes TEXT,
CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS InventoryHistory(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
InventoryId INTEGER NOT NULL,
ActionType TEXT NOT NULL,
OldEmployeeId INTEGER,
NewEmployeeId INTEGER,
Notes TEXT,
CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
CreatedByLoginUserId INTEGER
);

CREATE TABLE IF NOT EXISTS AssetRequestRecord(
Id Integer PRIMARY KEY AUTOINCREMENT,
EmployeeId INTEGER, 
AssetTypeId INTEGER, 
DateOfRequest DATETIME,
RequestedVia TEXT, 
ApprovedByLoginUserId INTEGER, 
ApprovedOn DATETIME, 
Notes TEXT, 
RequestCompleted INTEGER DEFAULT 0 
); 


-- INSERT OR IGNORE INTO LoginUsers
-- (Id, EmployeeId, Username, PasswordHash, Role, IsActive)
-- VALUES
-- (1, 1, 'admin', '$2b$10$qfacMEiLoDc8bZEzHL8wyeyZdz39YgdJ98AJXZICxIu3SDCgR/sGi', 'Admin', 1);